version: '3.8'

services:
  product-service:
    image: tanjag/ita-product-service:1.1.1
    ports:
      - "8080:8080"
    depends_on:
      - mongo_db
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo_db:27017/productDB
      SPRING_DATA_MONGODB_DATABASE: productDB
  mongo_db:
    image: mongo:7.0.6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: