version: '3.8'

services:
  product-service:
    image: tanjag/ita-product-service:1.0.0
    ports:
      - "8080:8080"
    depends_on:
      - mongo_db
    environment:
      SPRING_DATA_MONGODB_URI: ${MONGO_DB_URI}
      SPRING_DATA_MONGODB_DATABASE: ${MONGO_DB_DATABASE}

  mongo_db:
    image: mongo:7.0.6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: